### ISSUE TITLE
Feature suggestion.

### ISSUE THREAD

**Issue by Loderplay** [Half-People/HPCS2#1]
1.Can the outline of teammates be disabled, leaving only the outline of enemies?
2.It seems that the auto-aim function is not working.
3.After enabling the assistance, the graphics card fan runs at maximum speed. Is it possible to reduce or improve this issue?
Finally, thank you to the author for creating this.

**Comment by banovers** [comment]
Do I need to establish a branch? I have already resolved these issues

**Comment by Half-People** [comment]
> Do I need to establish a branch? I have already resolved these issues

i think you can ，I don’t plan to update this project for a long time， thx

**Comment by Half-People** [comment]
> 1.Can the outline of teammates be disabled, leaving only the outline of enemies? 2.It seems that the auto-aim function is not working. 3.After enabling the assistance, the graphics card fan runs at maximum speed. Is it possible to reduce or improve this issue? Finally, thank you to the author for creating this.

Auto aim not working, The problem should come from the fact that CS is still under crazy development and the View Angle address among the characters has changed.  You can just update the feature code

**Comment by banovers** [comment]
I have created the branch. This issue can be closed now.
